trigger:
- pipeline_dubug

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    rm gradlew
    gradle wrapper
    ls -lFht
    ./gradlew assemble
    ls -lFht ./lib/build/outputs/**
  displayName: Build aar