# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- pipeline_dubug

pool:
  vmImage: ubuntu-latest

steps:
# - task: Gradle@3
#   inputs:
#     # workingDirectory: ''
#     gradleWrapperFile: 'gradlew'
#     gradleOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: false
#     # testResultsFiles: '**/TEST-*.xml'
#     tasks: 'assemble'
- script: |
    wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
    unzip -d . gradle-7.5-bin.zip
  displayName: Download Gradle 7.5
- script: |
    ls -lFht ./gradle-7.5/bin/gradle
    ./gradle-7.5/bin/gradle  wrapper
    ls -lFht ./gradle-7.5/bin/
    ./gradlew assemble
    # ./../../gradle-7.5/bin/gradle
  displayName: Build Bundle