trigger:
- pipeline_dubug

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    ./gradlew assemble
    ls -lFht ./build/**
    ls -lFht ./lib/build/**
    ls -lFht ./build/kotlin/**
  displayName: Build aar